import 'dart:io';
import 'package:recase/recase.dart';
import 'package:xml/xml.dart';

import 'validation.dart';
import 'xml_to_map.dart';

void main(List<String> args) {
  // File fontsConfigFile = File(args[0]);

  final File fontsConfigFile = File('./fonts/SimpleIcons.ttx');

  if (!fontsConfigFile.existsSync()) {
    print('config file not found');
    exit(0);
  }

  final String content = fontsConfigFile.readAsStringSync();
  final XmlDocument document = XmlDocument.parse(content);

  final Map<String, String> icons = xmlToIcons(document);

  final List<String> generatedOutput = <String>[
    "import 'package:flutter/widgets.dart';\n",
    "import 'icon_data.dart';\n\n",
    '// THIS FILE IS AUTOMATICALLY GENERATED!\n\n',
    '/// [SimpleIcons] offers the [IconData] of [https://simpleicons.org/]\n',
    'class SimpleIcons {\n'
  ];

  final List<String> generatedOutput2 = <String>[
    "import 'package:flutter/widgets.dart';\n",
    "import 'flutter_simple_icons.g.dart';\n",
    '// THIS FILE IS AUTOMATICALLY GENERATED!\n\n',
    '/// [SimpleIconsMap] offers the [Map<String, IconData>] of [https://simpleicons.org/]\n',
    'class SimpleIconsMap {\n',
    'static const Map<String, IconData> simpleIconsMap = <String, IconData>{\n'
  ];

  icons.forEach((String iconName, String iconUnicode) {
    iconName = validateVariableName(iconName);
    generatedOutput
        .add('''/// SimpleIcons $iconName [IconData] with Unicode $iconUnicode
        static const IconData ${ReCase(iconName).camelCase} = SimpleIconData($iconUnicode);\n''');
  });

  generatedOutput.add('}\n');

  // Create a map of  icon name and IconData
  icons.forEach((String iconName, String iconUnicode) {
    iconName = validateVariableName(iconName);
    generatedOutput2.add('''
      /// SimpleIcons $iconName [IconData] with Unicode $iconUnicode
      "${ReCase(iconName).camelCase}": SimpleIcons.${ReCase(iconName).camelCase},
    ''');
  });
  generatedOutput2.add('};\n\n');

  generatedOutput2
      .add('IconData? operator [] (String name) => simpleIconsMap[name];\n');

  generatedOutput2.add('}\n');

  final File output = File('./lib/src/flutter_simple_icons.g.dart');
  final File output2 = File('./lib/src/flutter_simple_icons_map.g.dart');
  output.writeAsStringSync(generatedOutput.join());
  output2.writeAsStringSync(generatedOutput2.join());
}
