name: Release
on:
  schedule:
    - cron: 0 0 * * 1,2,3,4,5
  workflow_dispatch:
  
jobs: 
  check_version:
    name: Check for Updates
    runs-on: ubuntu-latest
    outputs:
      update_needed: ${{ steps.compare.outputs.update_needed }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Mise (for jq)
        uses: jdx/mise-action@v2

      - name: Compare release versions
        id: compare
        working-directory: vendor/
        run: |
          simple_icons_version="$(curl --retry 5 -s https://api.github.com/repos/simple-icons/simple-icons/releases/latest | jq -r .tag_name)"
          local_version=$(jq -r '.dependencies."simple-icons" // .devDependencies."simple-icons" // empty' package.json | tr -d '^')
          
          echo "si=$simple_icons_version" >> $GITHUB_OUTPUT
          
          if [ "$local_version" != "$simple_icons_version" ]; then
            echo "New version detected: $simple_icons_version (Local: $local_version)"
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "Everything is up to date ($local_version). Stopping workflow."
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

  release:
    name: Release
    needs: check_version
    if: needs.check_version.outputs.update_needed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          # Ensure we are checked out on the develop branch
          ref: develop
          # Ensure custom credentials are used when pushing
          persist-credentials: false
          # Fetch everything so we can checkout master
          fetch-depth: 0
      
      - name: Install Tools via Mise
        uses: jdx/mise-action@v2

      - name: Load flutter packages
        run: flutter pub get

      - name: Build library
        working-directory: tool/
        run: bash ./build.sh

      - name: Set Version and Changelog
        working-directory: tool/
        run: bash ./set_version.sh

      - name: Commit
        run: |
          set -e
          echo "Set up git credential"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "Create a version bump commit"
          git add .
          git commit -m "Update simple_icons to v${{ needs.check_version.outputs.si }}"

      - name: Upload
        run: |
          set -e
          echo "Merge develop into master"
          git checkout master
          git merge develop -m "Release ${{ needs.check_version.outputs.si }}"
          echo "Set up remote using a Personal Access Token"
          git remote remove origin
          git remote add origin https://${{secrets.RELEASE_TOKEN}}@github.com/jlnrrg/simple_icons
          echo "Push develop first, to prevent conflicts with parallel activity"
          git push origin develop
          echo "Push master only after develop was safely pushed"
          git push origin master